### ISSUE TITLE
disabledColor

### ISSUE THREAD

**Issue by prashanttyson** [ajaykumargithub2114/timer_button#1]
disabledColor is not working

**Comment by santiagocarod** [comment]
Hi! I'm having the same issue, is there any way to work around this?

**Comment by Adakar** [comment]
Hi @ajaynonstopio 
I'd be happy to takeover that issue. It seems that the `disabledColor` is used for setting the button background/border color and not the text color as described in the docstring. I think the docstring should be updated.
> /// The color to use for this button's text when the button is disabled.

Moreover the supported button types are deprecated. How about replacing them with the ones suggested in documentation and then fixing the issue? This however, might break the backward compatibility.

**Comment by ajaykumargithub2114** [comment]
Resolved in timer_button: ^2.0.0
