### ISSUE TITLE
timer_button with null safety

### ISSUE THREAD

**Issue by areeg-naksho** [ajaykumargithub2114/timer_button#10]
is this plugin will be available with null safety?

**Comment by Adakar** [comment]
Hi @areeg-naksho 
I prepared a pull request #8 that should add support for the null safety. As you can see it was still not reviewed nor accepted/declined. Let's hope that @ajaykumargithub2114 finds a moment to check it soon :)
BR, Adakar

**Comment by ajaykumargithub2114** [comment]
Resolved in timer_button: ^2.0.0
