### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by evanholt1** [ajaykumargithub2114/timer_button#7]
Hello!

when using this package, in languages other than English, the timer is still displayed with the letter 's'.
We have a need to change this depending on the user's preferred language in our app
(change the property "secPostFix", or optionally pass it into the constructor).
Can this be achieved?

I know this is a simple issue, and would like to help do it myself, but honestly i don't really know how.

**Comment by ajaykumargithub2114** [comment]
Resolved in timer_button: ^2.0.0
